
function T = data_prep(varargin)

    path = './data/';
    T = readtable([path 'mf850-finalproject-data.csv'], 'Delimiter', ',', 'ReadVariableNames', true);

    % basic transform
    T.Date = datetime(T.Date);
    T.Sector = arrayfun(@categorize, T.Industry, 'UniformOutput', false);
    save('rawdata.mat', 'T')
    
end

function sector = categorize(industry)

    majors = {
        'consumer discretionary', 
        'consumer staples',
        'energy',
        'materials',
        'industrials',
        'healthcare',
        'financials',
        'information technology',
        'real estate',
        'communication services',
        'utilities',
        'other'
    };

    minors = {
        {'Airlines', 'Airports & Air Services', 'Beverages - Brewers', 'Beverages - Non-Alcoholic', ...
        'Beverages - Soft Drinks', 'Beverages - Wineries & Distilleries', 'Confectioners', ...
        'Consumer Electronics', 'Department Stores', 'Discount Stores', 'Electronic Gaming & Multimedia', ...
        'Entertainment', 'Furnishings, Fixtures & Appliances', 'Gambling', 'Home Improvement Retail', ...
        'Internet Retail', 'Leisure', 'Lodging', 'Luxury Goods', 'Pay TV', 'Recreational Vehicles', ...
        'Resorts & Casinos', 'Restaurants', 'Specialty Retail', 'Tobacco'},
        {'Apparel Manufacturing', 'Apparel Retail', 'Apparel Stores', 'Auto & Truck Dealerships', ...
        'Farm Products', 'Food Distribution', 'Footwear & Accessories', 'Grocery Stores', 'Household & Personal Products', ...
        'Packaged Foods', 'Packaging & Containers', 'Paper & Paper Products'},
        {'Oil & Gas Drilling', 'Oil & Gas E&P', 'Oil & Gas Equipment & Services', ...
        'Oil & Gas Integrated', 'Oil & Gas Midstream', 'Oil & Gas Refining & Marketing', 'Solar'},
        {'Agricultural Inputs', 'Aluminum', 'Building Materials', 'Building Products & Equipment', ...
        'Business Equipment', 'Business Equipment & Supplies', 'Chemicals', 'Coal', 'Coking Coal', ...
        'Copper', 'Farm & Construction Equipment', 'Farm & Heavy Construction Machinery', 'Gold', ...
        'Industrial Metals & Minerals', 'Lumber & Wood Production', 'Other Industrial Metals & Mining', ...
        'Other Precious Metals & Mining', 'Specialty Chemicals', 'Steel', 'Thermal Coal', 'Uranium'},
        {'Aerospace & Defense', 'Auto Manufacturers', 'Auto Parts', 'Diversified Industrials', ...
        'Engineering & Construction', 'Industrial Distribution', 'Integrated Freight & Logistics', ...
        'Marine Shipping', 'Metal Fabrication', 'Railroads', 'Scientific & Technical Instruments', ...
        'Shipping & Ports', 'Specialty Industrial Machinery', 'Textile Manufacturing', 'Tools & Accessories', ...
        'Trucking'},
        {'Biotechnology', 'Diagnostics & Research', 'Drug Manufacturers - General', ...
        'Drug Manufacturers - Major', 'Drug Manufacturers - Specialty & Generic', ...
        'Health Care Plans', 'Health Information Services', 'Healthcare Plans', 'Long-Term Care Facilities', ...
        'Medical Care', 'Medical Care Facilities', 'Medical Devices', ...
        'Medical Distribution', 'Medical Instruments & Supplies', 'Pharmaceutical Retailers'},
        {'Asset Management', 'Capital Markets', 'Credit Services', 'Financial Conglomerates', ...
        'Financial Data & Stock Exchanges', 'Insurance - Life', ...
        'Insurance - Specialty', 'Insurance Brokers', 'Mortgage Finance'},
        {'Computer Hardware', 'Computer Systems', 'Electronic Components', 'Electronics & Computer Distribution', ...
        'Information Technology Services', 'Internet Content & Information', 'Semiconductor Equipment & Materials', ...
        'Semiconductor Memory', 'Semiconductors', 'Software - Application', 'Software - Infrastructure'},
        {'Real Estate - Development', 'Real Estate Services', 'Rental & Leasing Services', 'Residential Construction'},
        {'Broadcasting', 'Broadcasting - Radio', 'Communication Equipment', 'Media - Diversified', 'Publishing', ...
        'Telecom Services'},
        {'Electrical Equipment & Parts', 'Pollution & Treatment Controls', 'Utilities - Diversified', ...
        'Utilities - Independent Power Producers', ...
        'Utilities - Regulated Electric', 'Utilities - Regulated Gas', ...
        'Utilities - Regulated Water', 'Utilities - Renewable', 'Waste Management'},
        {'Advertising Agencies', 'Business Services', 'Conglomerates', 'Consulting Services', ...
        'Education & Training Services', 'Personal Services', 'Security & Protection Services', ...
        'Specialty Business Services', 'Staffing & Employment Services', 'Staffing & Outsourcing Services',  ...
        'Travel Services'}
    };

    M = containers.Map(majors, minors, 'UniformValues', false);
    sector = 'other';
    for k = M.keys
        if ismember(industry, M(k{1}))
            sector = k{1};
            return;
        end;
    end;
    
end